//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog12Petrakov.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prog12Entities : DbContext
    {
        public prog12Entities()
            : base("name=prog12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RepairActs> RepairActs { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<Telephones> Telephones { get; set; }
        public virtual DbSet<TelephoneTypes> TelephoneTypes { get; set; }
        public virtual DbSet<TypesProblems> TypesProblems { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
