//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog12Petrakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id_Sale { get; set; }
        public int Id_Telephone { get; set; }
        public int Id_User { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public bool Issued { get; set; }
    
        public virtual Telephones Telephones { get; set; }
        public virtual Users Users { get; set; }
    }
}
