//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog12Petrakov.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Telephones()
        {
            this.RepairActs = new HashSet<RepairActs>();
            this.Sales = new HashSet<Sales>();
        }
    
        public int Id_Telephone { get; set; }
        public string NameTelephone { get; set; }
        public bool IsAvailable { get; set; }
        public int Id_TelephoneType { get; set; }
        public decimal Price { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepairActs> RepairActs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual TelephoneTypes TelephoneTypes { get; set; }
    }
}
